services:
  - type: web
    name: glaucoma-api
    env: python
    python:
      version: "3.9.13"
    buildCommand: |
      cd Backend && 
      python -m pip install --upgrade pip==23.0.1 setuptools==65.5.1 wheel==0.38.4 &&
      pip install --no-cache-dir -r requirements.txt
    startCommand: cd Backend && uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1