services:
  - type: web
    name: glaucoma-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:8000
    envVars:
      - key: PORT
        value: 8000
    workingDirectory: Backend
    autoDeploy: true
